authentication:
  admin:
    username: admin
    password: password
    # github_login: nning

# foreground_processing: true

# token_length: 8

# temp_links:
#   invalidate_after: 86400

# file_release_token: ooH3yathu9Eey2vi

# label_image:
#   bin: lib/label_image/label_image
#   graph: lib/label_image/inception_v3_2016_08_28_frozen.pb
#   labels: lib/label_image/imagenet_slim_labels.txt
#   threshold: 0.09

# disable_gallery_creation: true

icons:
  - sizes: 48x48
    src: /images/touch/48x48.png
    type: text/png
  - sizes: 72x72
    src: /images/touch/72x72.png
    type: text/png
  - sizes: 96x96
    src: /images/touch/96x96.png
    type: text/png
  - sizes: 144x144
    src: /images/touch/144x144.png
    type: text/png
  - sizes: 168x168
    src: /images/touch/168x168.png
    type: text/png
  - sizes: 192x192
    src: /images/touch/192x192.png
    type: text/png

sizes:
  medium: 850x>
